sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm run test

after_success:
  - docker build -t pdimanov/fib-react ./client
  - docker build -t pdimanov/fib-nginx ./nginx
  - docker build -t pdimanov/fib-server ./server
  - docker build -t pdimanov/fib-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pdimanov/fib-react
  - docker push pdimanov/fib-nginx
  - docker push pdimanov/fib-server
  - docker push pdimanov/fib-worker